name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  name-inp:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: '/src/index.js'
